# Game engine toolchain builder

FROM ubuntu as Linux_x86
RUN apt-get update -y && apt-get install curl build-essential cmake wget git clang libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev  -y
